name: Frontend
on:
  push:
    paths-ignore:
      - 'functions/**'
      - 'tests/rules/**'
      - 'firestore.indexes.json'
      - 'firestore.rules'
      - 'jest.rules.config.js'
      - .github/workflows/rules.yml
      - 'data/**'
      - '.dependabot/**'
      - README.md
  pull_request:
    paths-ignore:
      - 'functions/**'
      - 'tests/rules/**'
      - 'firestore.indexes.json'
      - 'firestore.rules'
      - 'jest.rules.config.js'
      - .github/workflows/rules.yml
      - 'data/**'
      - '.dependabot/**'
      - README.md
jobs:
  test-build-deploy:
    name: Test, build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - run: npm ci
      - run: npm run test:unit
      - run: npm run build -- --mode staging
      - name: Deploy to Firebase
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        uses: w9jds/firebase-action@master
        with:
          args: deploy --project staging --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
