name: Rules
on:
  push:
    paths:
      - tests/rules/**
      - firestore.indexes.json
      - firestore.rules
      - jest.rules.config.js
      - .github/workflows/rules.yml
  pull_request:
    paths:
      - tests/rules/**
      - firestore.indexes.json
      - firestore.rules
      - jest.rules.config.js
      - .github/workflows/rules.yml
jobs:
  test-deploy-rules:
    name: Test and deploy rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - uses: actions/setup-java@master
        with:
          java-version: 11
          java-package: jre
      - run: npm ci
      - run: npm i -g firebase-tools
      - name: Setup Firestore emulator
        run: firebase setup:emulators:firestore
      - name: Run tests on Firestore emulator
        run: firebase emulators:exec --only firestore 'npm run test:rules'
      - name: Deploy to Firebase
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
        run: firebase deploy --project staging --only firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
